import type { NextConfig } from 'next';

/**
 * Image hosts are derived from the configured API/storage origins rather than
 * hard-coded, so pointing the app at a different backend (or moving media to a
 * CDN) needs no code change here.
 */
function remoteHosts(): Array<{ protocol: 'http' | 'https'; hostname: string; port?: string; pathname: string }> {
  const candidates = [
    process.env.NEXT_PUBLIC_API_URL,
    process.env.INTERNAL_API_URL,
    process.env.NEXT_PUBLIC_STORAGE_URL,
  ].filter(Boolean) as string[];

  const seen = new Set<string>();
  const hosts: Array<{ protocol: 'http' | 'https'; hostname: string; port?: string; pathname: string }> = [];

  for (const candidate of candidates) {
    try {
      const url = new URL(candidate);
      // Only real web origins are valid image hosts. Without this check a
      // relative value like "/api" (which is what NEXT_PUBLIC_API_URL is set to
      // for same-origin hosting) can still parse on some platforms — Windows
      // shells rewrite it to "C:/.../api", which URL() reads as protocol "c:"
      // with an empty hostname. Next then rejects the whole config and the
      // production build fails.
      if ((url.protocol !== 'http:' && url.protocol !== 'https:') || !url.hostname) continue;
      const key = `${url.protocol}//${url.host}`;
      if (seen.has(key)) continue;
      seen.add(key);
      hosts.push({
        protocol: url.protocol.replace(':', '') as 'http' | 'https',
        hostname: url.hostname,
        port: url.port || undefined,
        pathname: '/**',
      });
    } catch {
      // A malformed URL should not take the build down; the host is skipped.
    }
  }

  // Cloudinary serves uploaded artwork when STORAGE_DRIVER=cloudinary. Only
  // this account's folder is reachable, and the delivery host is fixed, so it
  // is safe to allow unconditionally rather than requiring another env var.
  hosts.push({ protocol: 'https', hostname: 'res.cloudinary.com', pathname: '/**' });

  if (hosts.length === 1) {
    hosts.push({ protocol: 'http', hostname: 'localhost', port: '4000', pathname: '/**' });
  }
  return hosts;
}

/**
 * Origin of the API service, for the same-origin `/api/*` proxy below.
 *
 * Accepts several variables because they all describe the same thing, and a
 * deployment that sets only the one server-rendering needs would otherwise
 * silently ship without the proxy: `/api/*` would fall through to the app and
 * return its 404 page instead of reaching the backend. Any path (`/api`) is
 * discarded — only the origin is used.
 */
function backendOrigin(): string | null {
  for (const raw of [process.env.BACKEND_ORIGIN, process.env.INTERNAL_API_URL, process.env.NEXT_PUBLIC_API_URL]) {
    const value = raw?.trim();
    if (!value) continue;
    try {
      const url = new URL(value);
      // A relative value such as "/api" is not an origin; skip it.
      if (url.protocol !== 'http:' && url.protocol !== 'https:') continue;
      return url.origin;
    } catch {
      // Not a URL (relative path, typo) — try the next candidate.
    }
  }
  return null;
}

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  output: 'standalone',

  images: {
    remotePatterns: remoteHosts(),
    formats: ['image/avif', 'image/webp'],
    // Poster and thumbnail art is SVG generated by our own seeder; Next refuses
    // to optimise SVG unless this is set, and it is safe because every SVG is
    // served from our own storage origin.
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },

  /**
   * Same-origin API proxy for split hosting (frontend on Vercel, API on
   * Render).
   *
   * Without this the browser would call the API on a different registrable
   * domain, making the refresh cookie a third-party cookie — which Safari and
   * Brave block outright and Chrome is phasing out, so sign-in would fail for
   * many visitors. Proxying keeps every credentialed request first-party.
   *
   * Returned as a plain array, which Next treats as `afterFiles`: real routes
   * such as the frontend's own /api/healthz still win, and only unmatched
   * /api/* paths are forwarded. The NestJS global prefix is `api`, so the path
   * is passed through unchanged — never rewritten to /api/api.
   *
   * Unset BACKEND_ORIGIN (local Docker) means no rewrite at all: the browser
   * talks to http://localhost:4000 directly, exactly as before.
   *
   * Video is deliberately NOT proxied — signed media URLs point straight at the
   * backend origin, so streams never take an extra hop through Vercel.
   */
  async rewrites() {
    const origin = backendOrigin();
    if (!origin) return [];
    return [{ source: '/api/:path*', destination: `${origin}/api/:path*` }];
  },

  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=()' },
        ],
      },
    ];
  },
};

export default nextConfig;
