import {
  AnimeTitleKind,
  CommunityPostKind,
  ContactCategory,
  MediaKind,
  MediaProvider,
  PrismaClient,
  PublishStatus,
  RelationKind,
  ReportKind,
  ReportTargetType,
  RequestStatus,
  SubtitleFormat,
  TierLevel,
  UserRole,
  VideoQuality,
  WatchStatus,
} from '@prisma/client';
import bcrypt from 'bcrypt';
import { config as loadEnv } from 'dotenv';
import { resolve } from 'node:path';
import {
  AD_PLACEMENTS,
  ANIME,
  COMMUNITY_CATEGORIES,
  GENRES,
  MANA_RULES,
  PRODUCERS,
  RANKS,
  SITE_SETTINGS,
  STUDIOS,
  type SeedAnime,
} from './seed-data';
import { avatarSvg, bannerSvg, posterSvg, thumbnailSvg, writeArt } from './seed-art';

loadEnv();

const prisma = new PrismaClient();

const UPLOADS_ROOT = resolve(process.env.STORAGE_LOCAL_PATH ?? './storage/uploads');
const PUBLIC_BASE = (process.env.STORAGE_PUBLIC_BASE_URL ?? 'http://localhost:4000/uploads').replace(/\/$/, '');
const BCRYPT_ROUNDS = Number(process.env.BCRYPT_ROUNDS ?? 10);

/**
 * Demo media generated by scripts/generate-demo-media.ps1.
 *
 * Stored as storage-relative paths rather than absolute URLs so the
 * DIRECT_FILE provider reads them straight off disk and answers Range requests
 * natively — the same code path a real deployment uses for object storage.
 */
const DEMO = {
  sub: [
    { quality: VideoQuality.Q_1080P, path: 'demo/sub-1080p.mp4', width: 1920, height: 1080 },
    { quality: VideoQuality.Q_720P, path: 'demo/sub-720p.mp4', width: 1280, height: 720 },
    { quality: VideoQuality.Q_480P, path: 'demo/sub-480p.mp4', width: 854, height: 480 },
    { quality: VideoQuality.Q_360P, path: 'demo/sub-360p.mp4', width: 640, height: 360 },
  ],
  dub: [
    { quality: VideoQuality.Q_720P, path: 'demo/dub-720p.mp4', width: 1280, height: 720 },
    { quality: VideoQuality.Q_480P, path: 'demo/dub-480p.mp4', width: 854, height: 480 },
  ],
  subtitles: [
    { language: 'en', label: 'English', path: 'demo/en.vtt', isDefault: true },
    { language: 'bn', label: 'Bangla', path: 'demo/bn.vtt', isDefault: false },
  ],
  durationSeconds: 90,
  intro: { start: 5, end: 15 },
  outro: { start: 78, end: 88 },
};

const DEMO_USERS = [
  { username: 'hikari', displayName: 'Hikari', bio: 'Here for the slow ones. Will defend Midnight Ramen Diaries forever.', mana: 4210 },
  { username: 'tatsuya', displayName: 'Tatsuya', bio: 'Mecha only. Everything else is a warm-up.', mana: 2380 },
  { username: 'nozomi', displayName: 'Nozomi', bio: 'Subtitle timing perfectionist. Sorry in advance for the reports.', mana: 1655 },
  { username: 'kenji', displayName: 'Kenji', bio: 'I make tier lists nobody asked for.', mana: 980 },
  { username: 'ayame', displayName: 'Ayame', bio: 'Seasonal watcher. Three shows at a time, maximum.', mana: 540 },
  { username: 'rei_t', displayName: 'Rei', bio: 'New here.', mana: 120 },
];

function slugify(value: string): string {
  return value
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
}

function pick<T>(items: T[], index: number): T {
  return items[index % items.length];
}

async function main(): Promise<void> {
  console.log('Seeding AniZora…\n');

  // ---------------------------------------------------------------- taxonomy
  console.log('  taxonomy');
  const genres = new Map<string, string>();
  for (const [index, g] of GENRES.entries()) {
    const row = await prisma.genre.upsert({
      where: { name: g.name },
      create: { name: g.name, slug: slugify(g.name), color: g.color, description: g.description, order: index },
      update: { color: g.color, description: g.description, order: index },
    });
    genres.set(g.name, row.id);
  }

  const studios = new Map<string, string>();
  for (const s of STUDIOS) {
    const row = await prisma.studio.upsert({
      where: { name: s.name },
      create: { name: s.name, slug: slugify(s.name), description: s.description },
      update: { description: s.description },
    });
    studios.set(s.name, row.id);
  }

  const producers = new Map<string, string>();
  for (const name of PRODUCERS) {
    const row = await prisma.producer.upsert({
      where: { name },
      create: { name, slug: slugify(name) },
      update: {},
    });
    producers.set(name, row.id);
  }

  // ------------------------------------------------------------ gamification
  console.log('  ranks and Mana economy');
  const ranks: Array<{ id: string; requiredMana: number }> = [];
  for (const [index, r] of RANKS.entries()) {
    const row = await prisma.rank.upsert({
      where: { name: r.name },
      create: {
        name: r.name,
        slug: slugify(r.name),
        requiredMana: r.requiredMana,
        icon: r.icon,
        color: r.color,
        description: r.description,
        order: index,
      },
      update: { requiredMana: r.requiredMana, icon: r.icon, color: r.color, description: r.description, order: index },
    });
    ranks.push(row);
  }

  for (const rule of MANA_RULES) {
    await prisma.manaRule.upsert({
      where: { event: rule.event },
      create: { event: rule.event, amount: rule.amount, dailyLimit: rule.dailyLimit, description: rule.description },
      update: { amount: rule.amount, dailyLimit: rule.dailyLimit, description: rule.description },
    });
  }

  const rankFor = (mana: number) =>
    [...ranks].reverse().find((r) => mana >= r.requiredMana)?.id ?? ranks[0].id;

  // ------------------------------------------------------------------- users
  console.log('  users');
  const adminEmail = process.env.ADMIN_EMAIL ?? 'admin@anizora.local';
  const adminUsername = process.env.ADMIN_USERNAME ?? 'admin';
  const adminPassword = process.env.ADMIN_PASSWORD ?? 'ChangeMe123!';

  const adminAvatar = await writeArt(UPLOADS_ROOT, PUBLIC_BASE, 'avatars', 'admin.svg', avatarSvg(adminUsername));
  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    create: {
      email: adminEmail,
      username: adminUsername,
      displayName: 'Site Admin',
      passwordHash: await bcrypt.hash(adminPassword, BCRYPT_ROUNDS),
      role: UserRole.SUPER_ADMIN,
      emailVerifiedAt: new Date(),
      avatarUrl: adminAvatar,
      mana: 0,
      rankId: rankFor(0),
    },
    update: { role: UserRole.SUPER_ADMIN, avatarUrl: adminAvatar },
  });

  const demoPassword = await bcrypt.hash('Password123', BCRYPT_ROUNDS);
  const users = [];
  for (const [index, u] of DEMO_USERS.entries()) {
    const avatarUrl = await writeArt(UPLOADS_ROOT, PUBLIC_BASE, 'avatars', `${u.username}.svg`, avatarSvg(u.username));
    const row = await prisma.user.upsert({
      where: { email: `${u.username}@example.com` },
      create: {
        email: `${u.username}@example.com`,
        username: u.username,
        displayName: u.displayName,
        bio: u.bio,
        passwordHash: demoPassword,
        emailVerifiedAt: new Date(),
        avatarUrl,
        mana: u.mana,
        rankId: rankFor(u.mana),
        role: index === 0 ? UserRole.MODERATOR : UserRole.USER,
      },
      update: { mana: u.mana, rankId: rankFor(u.mana), avatarUrl, bio: u.bio },
    });
    users.push(row);
  }

  // --------------------------------------------------------------- catalogue
  console.log('  catalogue');
  const animeIds = new Map<string, string>();

  for (const entry of ANIME) {
    const slug = slugify(entry.titleEnglish);
    const posterUrl = await writeArt(
      UPLOADS_ROOT,
      PUBLIC_BASE,
      'posters',
      `${slug}.svg`,
      posterSvg(entry.titleEnglish, `${entry.type} · ${entry.releaseYear}`),
    );
    const bannerUrl = await writeArt(
      UPLOADS_ROOT,
      PUBLIC_BASE,
      'banners',
      `${slug}.svg`,
      bannerSvg(entry.titleEnglish, entry.tagline),
    );

    const anime = await prisma.anime.upsert({
      where: { slug },
      create: {
        slug,
        titleEnglish: entry.titleEnglish,
        titleJapanese: entry.titleJapanese,
        titleRomaji: entry.titleRomaji,
        synopsis: entry.synopsis,
        posterUrl,
        bannerUrl,
        type: entry.type,
        status: entry.status,
        season: entry.season,
        releaseYear: entry.releaseYear,
        airStartDate: new Date(entry.releaseYear, seasonMonth(entry.season), 6),
        airEndDate:
          entry.status === 'COMPLETED' ? new Date(entry.releaseYear, seasonMonth(entry.season) + 3, 20) : null,
        ageRating: entry.ageRating,
        source: entry.source,
        durationMinutes: entry.durationMinutes,
        totalEpisodes: entry.episodeCount,
        isFeatured: entry.featured ?? false,
        publishStatus:
          entry.status === 'UPCOMING' ? PublishStatus.PUBLISHED : PublishStatus.PUBLISHED,
        seoTitle: `Watch ${entry.titleEnglish} online`,
        seoDescription: entry.synopsis.slice(0, 300),
        studioId: studios.get(entry.studio) ?? null,
      },
      update: { posterUrl, bannerUrl, synopsis: entry.synopsis, isFeatured: entry.featured ?? false },
    });
    animeIds.set(entry.titleEnglish, anime.id);

    await prisma.animeGenre.deleteMany({ where: { animeId: anime.id } });
    await prisma.animeGenre.createMany({
      data: entry.genres
        .map((name) => genres.get(name))
        .filter((id): id is string => Boolean(id))
        .map((genreId) => ({ animeId: anime.id, genreId })),
      skipDuplicates: true,
    });

    await prisma.animeProducer.deleteMany({ where: { animeId: anime.id } });
    await prisma.animeProducer.createMany({
      data: entry.producers
        .map((name) => producers.get(name))
        .filter((id): id is string => Boolean(id))
        .map((producerId) => ({ animeId: anime.id, producerId })),
      skipDuplicates: true,
    });

    await prisma.animeTitle.deleteMany({ where: { animeId: anime.id } });
    await prisma.animeTitle.createMany({
      data: [
        { animeId: anime.id, title: entry.titleEnglish, kind: AnimeTitleKind.ENGLISH },
        { animeId: anime.id, title: entry.titleJapanese, kind: AnimeTitleKind.JAPANESE },
        { animeId: anime.id, title: entry.titleRomaji, kind: AnimeTitleKind.ROMAJI },
        ...entry.synonyms.map((title) => ({ animeId: anime.id, title, kind: AnimeTitleKind.SYNONYM })),
      ],
      skipDuplicates: true,
    });

    await seedEpisodes(anime.id, entry, slug);

    // Upcoming titles have no episodes yet, which is the honest state.
    if (entry.status !== 'UPCOMING') {
      const [sub, dub] = await Promise.all([
        prisma.episode.count({ where: { animeId: anime.id, hasSub: true, publishStatus: PublishStatus.PUBLISHED } }),
        prisma.episode.count({ where: { animeId: anime.id, hasDub: true, publishStatus: PublishStatus.PUBLISHED } }),
      ]);
      await prisma.anime.update({
        where: { id: anime.id },
        data: { subEpisodeCount: sub, dubEpisodeCount: dub },
      });
    }
  }

  // ---------------------------------------------------------- relations etc.
  console.log('  relations, featured slider and view history');
  await seedRelations(animeIds);
  await seedFeatured(animeIds);
  await seedViewStats(animeIds);

  // ------------------------------------------------------------ engagement
  console.log('  ratings, watchlists and comments');
  await seedEngagement(animeIds, users);

  console.log('  community board');
  await seedCommunity(animeIds, [admin, ...users]);

  console.log('  requests, reports and support inbox');
  await seedSupport(animeIds, users, admin.id);

  // ------------------------------------------------------------- site config
  console.log('  site settings and ad placements');
  for (const setting of SITE_SETTINGS) {
    await prisma.siteSetting.upsert({
      where: { key: setting.key },
      create: {
        key: setting.key,
        value: setting.value as never,
        group: setting.group,
        label: setting.label,
        isPublic: setting.isPublic,
      },
      update: { group: setting.group, label: setting.label, isPublic: setting.isPublic },
    });
  }

  for (const placement of AD_PLACEMENTS) {
    await prisma.adPlacement.upsert({
      where: { key: placement.key },
      create: {
        key: placement.key,
        name: placement.name,
        description: placement.description,
        order: placement.order,
        // Disabled with empty identifiers: nothing renders until the operator
        // supplies their own AdSense publisher and slot IDs.
        isEnabled: false,
        adClient: null,
        adSlot: null,
      },
      update: { name: placement.name, description: placement.description, order: placement.order },
    });
  }

  await prisma.adPlacement.upsert({
    where: { key: 'video_instream' },
    create: {
      key: 'video_instream',
      name: 'In-stream video ads (IMA/VAST)',
      description:
        'Pre/mid/post-roll via the Google IMA SDK. Requires a Google Ad Manager VAST tag — a standard AdSense display account does not grant in-stream video inventory.',
      type: 'VIDEO',
      isEnabled: false,
      order: 0,
      config: {
        vastTagUrl: '',
        preRoll: true,
        midRoll: true,
        postRoll: false,
        midRollIntervalSeconds: 600,
        midRollCuePoints: [45],
        frequencyCapPerHour: 4,
      },
    },
    update: {},
  });

  const counts = await summarise();
  console.log('\nSeed complete:');
  for (const [label, value] of Object.entries(counts)) {
    console.log(`  ${label.padEnd(20)} ${value}`);
  }
  console.log(`\n  Admin sign-in: ${adminEmail} / ${adminPassword}`);
  console.log('  Demo accounts: <username>@example.com / Password123');
  console.log('  Demo media is synthetic (ffmpeg test pattern + sine tone) — replace via the admin panel.\n');
}

function seasonMonth(season: SeedAnime['season']): number {
  return { WINTER: 0, SPRING: 3, SUMMER: 6, FALL: 9 }[season];
}

async function seedEpisodes(animeId: string, entry: SeedAnime, animeSlug: string): Promise<void> {
  if (entry.status === 'UPCOMING') return;

  const existing = await prisma.episode.count({ where: { animeId } });
  if (existing > 0) return;

  for (let n = 1; n <= entry.episodeCount; n += 1) {
    const title = entry.episodeTitles[n - 1] ?? `Episode ${n}`;
    const thumbnailUrl = await writeArt(
      UPLOADS_ROOT,
      PUBLIC_BASE,
      'thumbnails',
      `${animeSlug}-ep${n}.svg`,
      thumbnailSvg(entry.titleEnglish, n),
    );

    const episode = await prisma.episode.create({
      data: {
        animeId,
        number: n,
        title,
        description: `Demo episode ${n} of ${entry.titleEnglish}.`,
        thumbnailUrl,
        durationSeconds: entry.type === 'MOVIE' ? DEMO.durationSeconds : DEMO.durationSeconds,
        airDate: new Date(entry.releaseYear, seasonMonth(entry.season), 6 + (n - 1) * 7),
        hasSub: true,
        hasDub: entry.hasDub,
        introStart: DEMO.intro.start,
        introEnd: DEMO.intro.end,
        outroStart: DEMO.outro.start,
        outroEnd: DEMO.outro.end,
        publishStatus: PublishStatus.PUBLISHED,
      },
    });

    // Subtitled source: four real renditions, so quality switching is genuine.
    const subSource = await prisma.mediaSource.create({
      data: {
        episodeId: episode.id,
        label: 'Server 1',
        provider: MediaProvider.DIRECT_FILE,
        kind: MediaKind.SUB,
        audioLanguage: 'ja',
        audioLabel: 'Japanese',
        priority: 0,
        isDefault: true,
      },
    });
    await prisma.mediaVariant.createMany({
      data: DEMO.sub.map((v, i) => ({
        mediaSourceId: subSource.id,
        quality: v.quality,
        directUrl: v.path,
        mimeType: 'video/mp4',
        width: v.width,
        height: v.height,
        isDefault: i === 1,
      })),
    });

    // Dubbed source: a separate file, because a progressive MP4 carries one
    // audio track. Switching audio therefore switches source — honestly.
    if (entry.hasDub) {
      const dubSource = await prisma.mediaSource.create({
        data: {
          episodeId: episode.id,
          label: 'Server 1',
          provider: MediaProvider.DIRECT_FILE,
          kind: MediaKind.DUB,
          audioLanguage: 'en',
          audioLabel: 'English Dub',
          priority: 1,
        },
      });
      await prisma.mediaVariant.createMany({
        data: DEMO.dub.map((v, i) => ({
          mediaSourceId: dubSource.id,
          quality: v.quality,
          directUrl: v.path,
          mimeType: 'video/mp4',
          width: v.width,
          height: v.height,
          isDefault: i === 0,
        })),
      });
    }

    await prisma.subtitleTrack.createMany({
      data: DEMO.subtitles.map((s) => ({
        episodeId: episode.id,
        mediaSourceId: null,
        language: s.language,
        label: s.label,
        format: SubtitleFormat.VTT,
        url: s.path,
        isDefault: s.isDefault,
      })),
    });
  }
}

async function seedRelations(animeIds: Map<string, string>): Promise<void> {
  const pairs: Array<[string, string, RelationKind]> = [
    ['Crimson Vanguard', 'Thunderstep Academy', RelationKind.ALTERNATIVE],
    ['Starlight Requiem', 'Summer of Falling Stars', RelationKind.SIDE_STORY],
    ['Glass Horizon', 'Orbital Gardeners', RelationKind.SPIN_OFF],
    ['Echo Protocol Zero', 'Glass Horizon', RelationKind.ALTERNATIVE],
    ['Aether Blade Chronicles', 'Fangs of the Silver Moon', RelationKind.SEQUEL],
  ];

  for (const [from, to, kind] of pairs) {
    const a = animeIds.get(from);
    const b = animeIds.get(to);
    if (!a || !b) continue;
    await prisma.animeRelation.upsert({
      where: { animeId_relatedAnimeId: { animeId: a, relatedAnimeId: b } },
      create: { animeId: a, relatedAnimeId: b, kind },
      update: { kind },
    });
    await prisma.animeRecommendation.upsert({
      where: { animeId_recommendedAnimeId: { animeId: a, recommendedAnimeId: b } },
      create: { animeId: a, recommendedAnimeId: b, weight: 10 },
      update: {},
    });
  }
}

async function seedFeatured(animeIds: Map<string, string>): Promise<void> {
  const featured = ANIME.filter((a) => a.featured);
  for (const [index, entry] of featured.entries()) {
    const animeId = animeIds.get(entry.titleEnglish);
    if (!animeId) continue;
    await prisma.featuredAnime.upsert({
      where: { animeId },
      create: { animeId, headline: entry.titleEnglish, subtitle: entry.tagline, order: index, ctaLabel: 'Watch Now' },
      update: { headline: entry.titleEnglish, subtitle: entry.tagline, order: index },
    });
  }
}

/** Gives Trending Day/Week/Month something real to rank on a fresh install. */
async function seedViewStats(animeIds: Map<string, string>): Promise<void> {
  const ids = [...animeIds.values()];
  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);

  for (const [index, animeId] of ids.entries()) {
    let total = 0;
    for (let d = 0; d < 30; d += 1) {
      const day = new Date(today);
      day.setUTCDate(day.getUTCDate() - d);
      // Deterministic but varied: popular titles trend higher and decay slower.
      const base = 400 - index * 22;
      const views = Math.max(5, Math.round(base * Math.exp(-d / 14) * (0.7 + ((index * 7 + d * 13) % 11) / 18)));
      total += views;
      await prisma.animeViewStat.upsert({
        where: { animeId_day: { animeId, day } },
        create: { animeId, day, views },
        update: { views },
      });
    }
    await prisma.anime.update({
      where: { id: animeId },
      data: { viewCount: total, popularity: total },
    });
  }
}

async function seedEngagement(
  animeIds: Map<string, string>,
  users: Array<{ id: string }>,
): Promise<void> {
  const ids = [...animeIds.values()];
  const statuses = [
    WatchStatus.WATCHING,
    WatchStatus.COMPLETED,
    WatchStatus.PLAN_TO_WATCH,
    WatchStatus.ON_HOLD,
    WatchStatus.DROPPED,
  ];

  const commentBodies = [
    'The pacing in this one is doing something I have not seen in a while. Genuinely patient.',
    'Episode 4 completely recontextualises the first three. Worth sticking with.',
    'The background art alone is carrying half the mood here.',
    'I was ready to drop this at episode 2 and I am very glad I did not.',
    'Sound design deserves more credit than it is getting.',
    'This is the rare show where the quiet episodes are the strong ones.',
    'Rewatching with subtitles on and catching a lot I missed.',
    'Not sure the ending lands for me, but the journey absolutely did.',
  ];

  for (const [i, user] of users.entries()) {
    for (let k = 0; k < 6; k += 1) {
      const animeId = pick(ids, i * 5 + k);

      await prisma.watchlistEntry.upsert({
        where: { userId_animeId: { userId: user.id, animeId } },
        create: {
          userId: user.id,
          animeId,
          status: pick(statuses, i + k),
          progressEpisodes: (i + k) % 9,
        },
        update: {},
      });

      if (k % 2 === 0) {
        const score = 6 + ((i * 3 + k * 5) % 5);
        await prisma.rating.upsert({
          where: { userId_animeId: { userId: user.id, animeId } },
          create: { userId: user.id, animeId, score },
          update: { score },
        });
      }

      if (k % 3 === 0) {
        await prisma.favorite.upsert({
          where: { userId_animeId: { userId: user.id, animeId } },
          create: { userId: user.id, animeId },
          update: {},
        });
      }
    }
  }

  // Recompute the denormalised score columns from the ratings just written.
  for (const animeId of ids) {
    const aggregate = await prisma.rating.aggregate({
      where: { animeId },
      _avg: { score: true },
      _count: { _all: true },
    });
    const favouriteCount = await prisma.favorite.count({ where: { animeId } });
    await prisma.anime.update({
      where: { id: animeId },
      data: {
        score: Number((aggregate._avg.score ?? 0).toFixed(2)),
        scoreCount: aggregate._count._all,
        favoriteCount: favouriteCount,
      },
    });
  }

  // A few episode comments with a reply thread and some votes.
  const episodes = await prisma.episode.findMany({
    where: { number: { lte: 3 } },
    take: 12,
    select: { id: true },
    orderBy: { createdAt: 'asc' },
  });

  for (const [i, episode] of episodes.entries()) {
    const author = pick(users, i);
    const root = await prisma.comment.create({
      data: {
        userId: author.id,
        episodeId: episode.id,
        body: pick(commentBodies, i),
        upvoteCount: (i * 3) % 14,
      },
    });

    if (i % 2 === 0) {
      const replier = pick(users, i + 2);
      await prisma.comment.create({
        data: {
          userId: replier.id,
          episodeId: episode.id,
          parentId: root.id,
          body: 'Completely agree — the second half of that episode is the strongest stretch so far.',
          upvoteCount: i % 5,
        },
      });
      await prisma.comment.update({ where: { id: root.id }, data: { replyCount: 1 } });
    }
  }

  // Partial watch progress, so "Continue watching" has real entries.
  const firstEpisodes = await prisma.episode.findMany({
    where: { number: { in: [1, 2] } },
    take: 10,
    include: { anime: { select: { id: true } } },
    orderBy: { createdAt: 'asc' },
  });

  for (const [i, episode] of firstEpisodes.entries()) {
    const user = pick(users, i);
    const position = 18 + ((i * 11) % 50);
    await prisma.watchProgress.upsert({
      where: { userId_episodeId: { userId: user.id, episodeId: episode.id } },
      create: {
        userId: user.id,
        episodeId: episode.id,
        animeId: episode.anime.id,
        positionSeconds: position,
        durationSeconds: DEMO.durationSeconds,
        percent: Math.round((position / DEMO.durationSeconds) * 100),
      },
      update: {},
    });
    await prisma.watchHistory.create({
      data: { userId: user.id, episodeId: episode.id, animeId: episode.anime.id },
    });
  }
}

async function seedCommunity(
  animeIds: Map<string, string>,
  users: Array<{ id: string }>,
): Promise<void> {
  const categories = new Map<string, string>();
  for (const [index, c] of COMMUNITY_CATEGORIES.entries()) {
    const row = await prisma.communityCategory.upsert({
      where: { name: c.name },
      create: {
        name: c.name,
        slug: slugify(c.name),
        description: c.description,
        color: c.color,
        icon: c.icon,
        order: index,
        staffOnly: c.staffOnly ?? false,
      },
      update: { description: c.description, color: c.color, icon: c.icon, order: index },
    });
    categories.set(c.name, row.id);
  }

  if ((await prisma.communityPost.count()) > 0) return;

  const ids = [...animeIds.values()];

  const textPosts: Array<{ category: string; title: string; body: string; pinned?: boolean }> = [
    {
      category: 'Updates',
      title: 'Welcome to the AniZora community board',
      body: '<p>This is the place for discussion, recommendations, tier lists and polls. A few ground rules: tag spoilers, keep it civil, and use the report button rather than arguing with someone who is clearly baiting.</p><p>Posting and commenting earn Mana, which advances your rank. Ranks are cosmetic — they signal that someone has been around, nothing more.</p>',
      pinned: true,
    },
    {
      category: 'Discussion',
      title: 'Shows where the quiet episodes are the strongest',
      body: '<p>I keep noticing that the episodes I remember are almost never the big ones. Midnight Ramen Diaries is the obvious example but Starlight Requiem does it too — the rehearsal episodes land harder than the performance.</p><p>What else fits?</p>',
    },
    {
      category: 'Question',
      title: 'How do I get subtitles to stay on between episodes?',
      body: '<p>Every time autoplay moves to the next episode my subtitle selection resets. Am I missing a setting somewhere?</p>',
    },
    {
      category: 'Suggestion',
      title: 'Per-series default audio preference',
      body: '<p>I watch some things subbed and some dubbed, and a single global preference does not really capture that. Would it be possible to remember the choice per series instead?</p>',
    },
    {
      category: 'Seasonal',
      title: 'Fall 2026 — what is everyone actually keeping?',
      body: '<p>Three episodes in for most things now. I have dropped more than I have kept this season, which is unusual. Crimson Vanguard and Ironheart Meridian are the only two I am still genuinely looking forward to.</p>',
    },
    {
      category: 'Feedback',
      title: 'The A-Z browser is much faster than it used to be',
      body: '<p>Whatever changed on the listing pages, it is noticeably quicker on mobile. Wanted to say so rather than only posting when something breaks.</p>',
    },
  ];

  for (const [i, post] of textPosts.entries()) {
    const categoryId = categories.get(post.category);
    if (!categoryId) continue;
    await prisma.communityPost.create({
      data: {
        userId: pick(users, i).id,
        categoryId,
        title: post.title,
        slug: slugify(post.title),
        body: post.body,
        kind: CommunityPostKind.TEXT,
        isPinned: post.pinned ?? false,
        upvoteCount: 4 + i * 3,
        viewCount: 60 + i * 37,
      },
    });
  }

  // --- A poll -------------------------------------------------------------
  const pollPost = await prisma.communityPost.create({
    data: {
      userId: pick(users, 1).id,
      categoryId: categories.get('Poll')!,
      title: 'Which format do you actually prefer for a long-running series?',
      slug: slugify('Which format do you actually prefer for a long running series'),
      body: '<p>Curious how this splits. Assume the production quality is identical either way.</p>',
      kind: CommunityPostKind.POLL,
      upvoteCount: 22,
      viewCount: 410,
    },
  });
  const poll = await prisma.poll.create({
    data: { postId: pollPost.id, question: 'Preferred release format?', totalVotes: 0 },
  });
  await prisma.pollOption.createMany({
    data: [
      { pollId: poll.id, text: 'Weekly episodes', order: 0, voteCount: 41 },
      { pollId: poll.id, text: 'Full season at once', order: 1, voteCount: 27 },
      { pollId: poll.id, text: 'Two-episode weekly blocks', order: 2, voteCount: 14 },
      { pollId: poll.id, text: 'Cour splits with a break', order: 3, voteCount: 9 },
    ],
  });
  await prisma.poll.update({ where: { id: poll.id }, data: { totalVotes: 91 } });

  // --- A matchup (a poll with exactly two options) -------------------------
  const matchupPost = await prisma.communityPost.create({
    data: {
      userId: pick(users, 3).id,
      categoryId: categories.get('Matchup')!,
      title: 'Glass Horizon vs Echo Protocol Zero — which handles institutional failure better?',
      slug: slugify('Glass Horizon vs Echo Protocol Zero'),
      body: '<p>Both are about a system quietly failing while everyone involved has a reason not to escalate. Which one sticks the landing?</p>',
      kind: CommunityPostKind.MATCHUP,
      upvoteCount: 31,
      viewCount: 620,
    },
  });
  const matchupPoll = await prisma.poll.create({
    data: { postId: matchupPost.id, question: 'Pick one', totalVotes: 58 },
  });
  await prisma.pollOption.createMany({
    data: [
      { pollId: matchupPoll.id, text: 'Glass Horizon', order: 0, voteCount: 33, animeId: animeIds.get('Glass Horizon') },
      { pollId: matchupPoll.id, text: 'Echo Protocol Zero', order: 1, voteCount: 25, animeId: animeIds.get('Echo Protocol Zero') },
    ],
  });

  // --- A tier list --------------------------------------------------------
  const tierPost = await prisma.communityPost.create({
    data: {
      userId: pick(users, 2).id,
      categoryId: categories.get('Tier List')!,
      title: 'My completely indefensible 2025 tier list',
      slug: slugify('My completely indefensible 2025 tier list'),
      body: '<p>Ranked purely on how often I have thought about them since finishing. Argue in the comments.</p>',
      kind: CommunityPostKind.TIER_LIST,
      upvoteCount: 18,
      viewCount: 295,
    },
  });
  const tierAssignments: Array<[string, TierLevel]> = [
    ['Starlight Requiem', TierLevel.S],
    ['Glass Horizon', TierLevel.S],
    ['Midnight Ramen Diaries', TierLevel.A],
    ['Echo Protocol Zero', TierLevel.A],
    ['The Last Alchemy Club', TierLevel.B],
    ['Summer of Falling Stars', TierLevel.B],
    ['Paper Lanterns of Yomi', TierLevel.C],
  ];
  await prisma.tierListItem.createMany({
    data: tierAssignments
      .filter(([title]) => animeIds.has(title))
      .map(([title, tier], order) => ({
        postId: tierPost.id,
        tier,
        label: title,
        animeId: animeIds.get(title)!,
        order,
      })),
  });

  // --- A recommendation post ----------------------------------------------
  const recPost = await prisma.communityPost.create({
    data: {
      userId: pick(users, 4).id,
      categoryId: categories.get('Recommend')!,
      title: 'Three shows to watch if you like competence over spectacle',
      slug: slugify('Three shows to watch if you like competence over spectacle'),
      body: '<p>All three are about people who are very good at unglamorous jobs. No chosen ones, no tournaments.</p>',
      kind: CommunityPostKind.RECOMMENDATION,
      upvoteCount: 26,
      viewCount: 380,
    },
  });
  const recTitles = ['Orbital Gardeners', 'Glass Horizon', 'Ironheart Meridian'];
  await prisma.communityPostAnime.createMany({
    data: recTitles
      .filter((t) => animeIds.has(t))
      .map((t, order) => ({
        postId: recPost.id,
        animeId: animeIds.get(t)!,
        order,
        note: 'Quietly excellent at what it sets out to do.',
      })),
  });

  // Comments across the board.
  const posts = await prisma.communityPost.findMany({ select: { id: true } });
  const replies = [
    'Strong agree on the second one. The third is a harder sell but it got me eventually.',
    'This is a good list and I am annoyed that I cannot argue with any of it.',
    'Bookmarking. Half of these have been on my list for months.',
    'Interesting framing — I had not thought about it that way.',
  ];
  for (const [i, post] of posts.entries()) {
    const count = (i % 3) + 1;
    for (let k = 0; k < count; k += 1) {
      await prisma.communityComment.create({
        data: {
          postId: post.id,
          userId: pick(users, i + k + 1).id,
          body: pick(replies, i + k),
          upvoteCount: (i + k) % 7,
        },
      });
    }
    await prisma.communityPost.update({ where: { id: post.id }, data: { commentCount: count } });
  }
}

async function seedSupport(
  animeIds: Map<string, string>,
  users: Array<{ id: string }>,
  adminId: string,
): Promise<void> {
  if ((await prisma.animeRequest.count()) === 0) {
    await prisma.animeRequest.createMany({
      data: [
        {
          userId: users[0].id,
          title: 'Harbour Lights Overture',
          titleJapanese: '港灯序曲',
          message: 'A 2023 slice-of-life about a dockside brass band. Hard to find anywhere.',
          status: RequestStatus.REVIEWING,
        },
        {
          userId: users[2].id,
          title: 'The Cartographer of Small Hours',
          message: 'Short film, roughly 40 minutes. Would love to see it added.',
          status: RequestStatus.APPROVED,
          adminNote: 'Licensing confirmed, encoding in progress.',
        },
        {
          userId: users[3].id,
          title: 'Iron Kite',
          message: 'Sequel to something already on the site.',
          status: RequestStatus.PENDING,
        },
        {
          userId: users[1].id,
          title: 'Winterbourne Station',
          message: 'Requested a while ago — any update?',
          status: RequestStatus.REJECTED,
          adminNote: 'No distribution rights available in our regions.',
          resolvedAt: new Date(),
        },
      ],
    });
  }

  if ((await prisma.report.count()) === 0) {
    const episode = await prisma.episode.findFirst({ select: { id: true } });
    if (episode) {
      await prisma.report.createMany({
        data: [
          {
            userId: users[2].id,
            targetType: ReportTargetType.EPISODE,
            targetId: episode.id,
            kind: ReportKind.SUBTITLE_NOT_SYNCED,
            message: 'English subtitles drift about two seconds late from roughly the midpoint onward.',
            context: { source: 'Server 1', quality: '1080p', positionSeconds: 52 },
          },
          {
            userId: users[4].id,
            targetType: ReportTargetType.EPISODE,
            targetId: episode.id,
            kind: ReportKind.INCORRECT_TIMESTAMPS,
            message: 'Skip Intro jumps past the first line of dialogue.',
            status: 'INVESTIGATING',
            context: { introStart: 5, introEnd: 15 },
          },
        ],
      });
    }
  }

  if ((await prisma.contactMessage.count()) === 0) {
    await prisma.contactMessage.createMany({
      data: [
        {
          name: 'Priya N.',
          email: 'priya@example.com',
          subject: 'Advertising enquiry',
          category: ContactCategory.ADVERTISING,
          message: 'We would like to discuss a seasonal placement on the homepage. Who is the right person to contact?',
        },
        {
          name: 'Daniel R.',
          email: 'daniel@example.com',
          subject: 'Player stalls on mobile data',
          category: ContactCategory.TECHNICAL,
          message: 'On 4G the player buffers every 20 seconds at 1080p but is fine at 720p. Pixel 7, Chrome.',
          status: 'OPEN',
        },
      ],
    });
  }

  void animeIds;
  void adminId;
}

async function summarise(): Promise<Record<string, number>> {
  const [anime, episodes, sources, variants, subtitles, users, posts, comments, requests] = await Promise.all([
    prisma.anime.count(),
    prisma.episode.count(),
    prisma.mediaSource.count(),
    prisma.mediaVariant.count(),
    prisma.subtitleTrack.count(),
    prisma.user.count(),
    prisma.communityPost.count(),
    prisma.comment.count(),
    prisma.animeRequest.count(),
  ]);
  return {
    anime,
    episodes,
    'media sources': sources,
    'quality variants': variants,
    'subtitle tracks': subtitles,
    users,
    'community posts': posts,
    comments,
    'anime requests': requests,
  };
}

main()
  .catch((error) => {
    console.error('\nSeed failed:', error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
