import {
  AgeRating,
  AnimeSeason,
  AnimeSource,
  AnimeStatus,
  AnimeType,
  ContactCategory,
  ManaEvent,
} from '@prisma/client';

/**
 * Demo catalogue.
 *
 * Every title, studio, producer and synopsis below is an original invention
 * written for this project. No real series, character, studio or artwork is
 * referenced, and nothing was scraped from a metadata service — which is both
 * the safe choice and the one the brief asks for. Replace it all through the
 * admin panel once real, licensed content is available.
 */

export const GENRES: Array<{ name: string; color: string; description: string }> = [
  { name: 'Action', color: '#ff4d5e', description: 'Kinetic combat and high-stakes confrontation.' },
  { name: 'Adventure', color: '#ffa94d', description: 'Journeys into the unknown.' },
  { name: 'Comedy', color: '#ffd93d', description: 'Built to make you laugh.' },
  { name: 'Drama', color: '#c77dff', description: 'Character-driven emotional weight.' },
  { name: 'Fantasy', color: '#7c5cff', description: 'Magic, myth and invented worlds.' },
  { name: 'Sci-Fi', color: '#22e1c8', description: 'Speculative technology and futures.' },
  { name: 'Slice of Life', color: '#8ee3ef', description: 'The texture of ordinary days.' },
  { name: 'Mystery', color: '#5c7cfa', description: 'Questions that demand an answer.' },
  { name: 'Romance', color: '#ff7eb3', description: 'Love, longing and everything between.' },
  { name: 'Supernatural', color: '#9775fa', description: 'Beyond the explainable.' },
  { name: 'Sports', color: '#51cf66', description: 'Training, rivalry and the final whistle.' },
  { name: 'Thriller', color: '#ff6b6b', description: 'Tension that refuses to let go.' },
  { name: 'Music', color: '#ffc078', description: 'Performance, sound and the people making it.' },
  { name: 'Historical', color: '#d4a373', description: 'Stories rooted in the past.' },
  { name: 'Mecha', color: '#4dabf7', description: 'Piloted machines and the people inside them.' },
  { name: 'Psychological', color: '#845ef7', description: 'The mind as the real battlefield.' },
  { name: 'Horror', color: '#e03131', description: 'Dread, and what waits in it.' },
  { name: 'Isekai', color: '#20c997', description: 'Carried into another world.' },
  { name: 'School', color: '#74c0fc', description: 'Classrooms, clubs and the years between.' },
  { name: 'Martial Arts', color: '#f76707', description: 'Discipline expressed through the body.' },
  { name: 'Iyashikei', color: '#a9e34b', description: 'Gentle, healing and unhurried.' },
  { name: 'Seinen', color: '#adb5bd', description: 'Aimed at an adult audience.' },
  { name: 'Shounen', color: '#ff922b', description: 'Growth, friendship and escalation.' },
  { name: 'Shoujo', color: '#faa2c1', description: 'Emotional intimacy and interior life.' },
];

export const STUDIOS: Array<{ name: string; description: string }> = [
  { name: 'Studio Lumen', description: 'Known for layered lighting work and restrained character animation.' },
  { name: 'Kitsune Works', description: 'A small team with an outsized reputation for action choreography.' },
  { name: 'Aoi Frame', description: 'Specialises in colour scripting and atmospheric backgrounds.' },
  { name: 'Nova Sakura', description: 'Hybrid 2D/3D pipeline built for large-scale set pieces.' },
  { name: 'Studio Karakuri', description: 'Mechanical design house turned full production studio.' },
  { name: 'Hoshikawa Animation', description: 'Long-running studio with a deep in-house training programme.' },
  { name: 'Third Bell Studio', description: 'Independent outfit focused on quiet, character-first storytelling.' },
];

export const PRODUCERS: string[] = [
  'Hoshizora Media',
  'Tenjin Publishing',
  'Bluewave Records',
  'Sakuraba Committee',
  'Lantern Partners',
  'Kagami Broadcasting',
];

export interface SeedAnime {
  titleEnglish: string;
  titleJapanese: string;
  titleRomaji: string;
  synonyms: string[];
  tagline: string;
  synopsis: string;
  type: AnimeType;
  status: AnimeStatus;
  season: AnimeSeason;
  releaseYear: number;
  ageRating: AgeRating;
  source: AnimeSource;
  durationMinutes: number;
  episodeCount: number;
  hasDub: boolean;
  studio: string;
  producers: string[];
  genres: string[];
  featured?: boolean;
  episodeTitles: string[];
}

export const ANIME: SeedAnime[] = [
  {
    titleEnglish: 'Crimson Vanguard',
    titleJapanese: 'クリムゾン・ヴァンガード',
    titleRomaji: 'Kurimuzon Vangaado',
    synonyms: ['Kurenai no Senei'],
    tagline: 'The wall holds, or nothing does.',
    synopsis:
      'For eleven years the border city of Akatsuka has been shielded by a lattice of signal towers nobody fully understands. When the southern tower goes dark, a decommissioned squad of relay engineers is the only unit close enough to reach it before dawn. What they find inside is not a malfunction. Told largely from the perspective of the people who maintain the defences rather than the ones who command them, Crimson Vanguard is a story about the unglamorous work that keeps a city alive — and the cost of discovering that the thing you have been protecting was never quite what you were told.',
    type: AnimeType.TV,
    status: AnimeStatus.ONGOING,
    season: AnimeSeason.FALL,
    releaseYear: 2026,
    ageRating: AgeRating.R_17,
    source: AnimeSource.MANGA,
    durationMinutes: 24,
    episodeCount: 12,
    hasDub: true,
    studio: 'Kitsune Works',
    producers: ['Hoshizora Media', 'Tenjin Publishing'],
    genres: ['Action', 'Drama', 'Mystery', 'Shounen'],
    featured: true,
    episodeTitles: [
      'The Southern Tower',
      'Signal Decay',
      'What the Engineers Knew',
      'Dawn Protocol',
      'Nobody Files a Report',
      'The Lattice',
      'Thirty-One Hours',
      'Relay',
      'The Second Wall',
      'Names on the Roster',
      'Everything We Were Told',
      'The Wall Holds',
    ],
  },
  {
    titleEnglish: 'Starlight Requiem',
    titleJapanese: 'スターライト・レクイエム',
    titleRomaji: 'Sutaaraito Rekuiemu',
    synonyms: ['Hoshi no Banka'],
    tagline: 'Some songs are meant to be finished by someone else.',
    synopsis:
      'Composer Mizuki Serizawa died leaving a symphony three movements short. Her four former students — none of whom have spoken since the funeral — are summoned to a coastal conservatory and told they will complete it together or not at all. Starlight Requiem moves slowly and deliberately, letting arguments about tempo stand in for arguments about grief, and treating the act of finishing someone else’s work as the most difficult kind of mourning there is.',
    type: AnimeType.TV,
    status: AnimeStatus.COMPLETED,
    season: AnimeSeason.SPRING,
    releaseYear: 2025,
    ageRating: AgeRating.PG_13,
    source: AnimeSource.ORIGINAL,
    durationMinutes: 24,
    episodeCount: 12,
    hasDub: true,
    studio: 'Studio Lumen',
    producers: ['Bluewave Records', 'Lantern Partners'],
    genres: ['Drama', 'Music', 'Slice of Life', 'Seinen'],
    featured: true,
    episodeTitles: [
      'Three Movements Short',
      'The Coastal Conservatory',
      'Tempo Disagreement',
      'What She Left in the Margins',
      'First Read-Through',
      'The Cellist Who Quit',
      'Rest, Two Bars',
      'Everyone Remembers It Differently',
      'The Fourth Student',
      'Rehearsal in the Dark',
      'Final Movement',
      'Requiem',
    ],
  },
  {
    titleEnglish: 'Neon Sakura Drift',
    titleJapanese: 'ネオン桜ドリフト',
    titleRomaji: 'Neon Sakura Dorifuto',
    synonyms: ['NSD'],
    tagline: 'Win the corner, lose the night.',
    synopsis:
      'Street racing in the rebuilt Shinkai districts is less about speed than about reading the road surface, and nobody reads it like Rei Tachibana — who has not raced in two years and does not intend to start again. When her younger brother signs her name onto a circuit she swore off, Rei is pulled back into a scene that has moved on without her. A sports drama about technique, reputation, and the particular humiliation of being outclassed by people who learned from watching you.',
    type: AnimeType.TV,
    status: AnimeStatus.ONGOING,
    season: AnimeSeason.SUMMER,
    releaseYear: 2026,
    ageRating: AgeRating.PG_13,
    source: AnimeSource.MANGA,
    durationMinutes: 23,
    episodeCount: 10,
    hasDub: false,
    studio: 'Nova Sakura',
    producers: ['Kagami Broadcasting'],
    genres: ['Action', 'Sports', 'Drama', 'Shounen'],
    featured: true,
    episodeTitles: [
      'Someone Signed My Name',
      'Reading the Surface',
      'Two Years of Rust',
      'The Kanata Line',
      'Downshift',
      'People Who Learned From Watching You',
      'Wet Asphalt',
      'The Corner at Kilometre Nine',
      'Reputation',
      'Drift',
    ],
  },
  {
    titleEnglish: 'The Last Alchemy Club',
    titleJapanese: '最後の錬金部',
    titleRomaji: 'Saigo no Renkinbu',
    synonyms: ['Alchemy Club'],
    tagline: 'Four members. One budget. Zero supervision.',
    synopsis:
      'Kurobane Academy is closing every club that cannot demonstrate "measurable academic value", which puts the Alchemy Club — four students, one hotplate, and a cupboard of reagents nobody has audited since 1998 — firmly on the list. Their plan to save it involves a demonstration none of them are qualified to attempt. A warm, fast comedy about institutional absurdity and the specific loyalty of people who have blown something up together.',
    type: AnimeType.TV,
    status: AnimeStatus.COMPLETED,
    season: AnimeSeason.WINTER,
    releaseYear: 2025,
    ageRating: AgeRating.PG,
    source: AnimeSource.FOUR_KOMA,
    durationMinutes: 23,
    episodeCount: 12,
    hasDub: true,
    studio: 'Third Bell Studio',
    producers: ['Tenjin Publishing', 'Sakuraba Committee'],
    genres: ['Comedy', 'School', 'Slice of Life'],
    episodeTitles: [
      'Measurable Academic Value',
      'The Cupboard Audit',
      'One Hotplate',
      'Recruitment Drive',
      'The Budget Meeting',
      'Something Turned Green',
      'Faculty Advisor Wanted',
      'The Rival Club',
      'Fire Drill',
      'Dress Rehearsal',
      'The Demonstration',
      'Still Standing',
    ],
  },
  {
    titleEnglish: 'Aether Blade Chronicles',
    titleJapanese: 'エーテルブレイド戦記',
    titleRomaji: 'Eeteru Bureido Senki',
    synonyms: ['ABC', 'Aetherblade'],
    tagline: 'A sword that remembers every hand that held it.',
    synopsis:
      'The Aether Blade chooses its bearer once a generation and discards them without ceremony when it is done. Sixteen-year-old Ilen Vask is the first person in four hundred years to refuse it — and the blade, having no precedent for this, simply follows her. A high fantasy adventure that is far more interested in what a legendary weapon does to the people around its wielder than in the wielder herself.',
    type: AnimeType.TV,
    status: AnimeStatus.ONGOING,
    season: AnimeSeason.SPRING,
    releaseYear: 2026,
    ageRating: AgeRating.PG_13,
    source: AnimeSource.LIGHT_NOVEL,
    durationMinutes: 24,
    episodeCount: 12,
    hasDub: true,
    studio: 'Hoshikawa Animation',
    producers: ['Hoshizora Media', 'Lantern Partners'],
    genres: ['Fantasy', 'Adventure', 'Action', 'Drama'],
    featured: true,
    episodeTitles: [
      'The Refusal',
      'No Precedent',
      'Four Hundred Years',
      'The Bearer Before Her',
      'Every Hand That Held It',
      'The Cartographer',
      'Weight',
      'What the Blade Wants',
      'The Discarded',
      'Ilen Alone',
      'Inheritance',
      'The Choosing',
    ],
  },
  {
    titleEnglish: 'Midnight Ramen Diaries',
    titleJapanese: '深夜ラーメン日記',
    titleRomaji: 'Shinya Raamen Nikki',
    synonyms: [],
    tagline: 'Open from midnight. Closed when the broth runs out.',
    synopsis:
      'A twelve-seat counter in a side street that opens at midnight and closes whenever the broth is gone. Each episode follows one customer through one bowl. No arcs, no escalation, no plot to speak of — just the accumulating portrait of a neighbourhood told through the people who cannot sleep in it.',
    type: AnimeType.TV,
    status: AnimeStatus.COMPLETED,
    season: AnimeSeason.FALL,
    releaseYear: 2024,
    ageRating: AgeRating.PG,
    source: AnimeSource.MANGA,
    durationMinutes: 22,
    episodeCount: 12,
    hasDub: false,
    studio: 'Third Bell Studio',
    producers: ['Sakuraba Committee'],
    genres: ['Slice of Life', 'Iyashikei', 'Drama', 'Seinen'],
    episodeTitles: [
      'The Night Shift Nurse',
      'Extra Chashu',
      'The Man Who Comes Every Tuesday',
      'Closing Early',
      'Two Bowls, One Seat',
      'The Taxi Driver',
      'Salt, Not Soy',
      'Rain Until Four',
      'The Regular Who Stopped Coming',
      'Apprentice',
      'The Last Bowl',
      'Until the Broth Runs Out',
    ],
  },
  {
    titleEnglish: 'Glass Horizon',
    titleJapanese: 'ガラスの地平',
    titleRomaji: 'Garasu no Chihei',
    synonyms: ['Glasshorizon'],
    tagline: 'The colony was designed to last two hundred years. It is on year three.',
    synopsis:
      'Orbital habitat Meridian was built to be self-sufficient for two centuries. Thirty-one months in, the atmospheric processors are failing in a pattern that the original engineers explicitly ruled out. Systems analyst Toma Ishigaki is assigned to find the fault and instead finds the design review that predicted it. A patient, procedural science fiction drama about institutional accountability at a distance from which nobody can be held accountable.',
    type: AnimeType.TV,
    status: AnimeStatus.COMPLETED,
    season: AnimeSeason.SUMMER,
    releaseYear: 2025,
    ageRating: AgeRating.R_17,
    source: AnimeSource.NOVEL,
    durationMinutes: 25,
    episodeCount: 11,
    hasDub: true,
    studio: 'Studio Karakuri',
    producers: ['Kagami Broadcasting', 'Hoshizora Media'],
    genres: ['Sci-Fi', 'Mystery', 'Psychological', 'Drama', 'Seinen'],
    episodeTitles: [
      'Month Thirty-One',
      'The Pattern They Ruled Out',
      'Design Review 44-C',
      'Atmospheric Tolerance',
      'Nobody Signs Their Name',
      'The Original Engineers',
      'Two Hundred Years',
      'Failure Mode',
      'Distance',
      'The Report',
      'Glass Horizon',
    ],
  },
  {
    titleEnglish: 'Thunderstep Academy',
    titleJapanese: '雷歩学園',
    titleRomaji: 'Raiho Gakuen',
    synonyms: [],
    tagline: 'Talent gets you in. Nothing about that helps afterwards.',
    synopsis:
      'Every student at Thunderstep was the best in their region. That is the entry requirement, and it stops being an advantage the moment the doors close. A martial arts school story that focuses on the second-years — the ones who have already discovered they are ordinary here — and on what it takes to keep training once the story is no longer about you.',
    type: AnimeType.TV,
    status: AnimeStatus.ONGOING,
    season: AnimeSeason.WINTER,
    releaseYear: 2026,
    ageRating: AgeRating.PG_13,
    source: AnimeSource.MANGA,
    durationMinutes: 24,
    episodeCount: 12,
    hasDub: true,
    studio: 'Kitsune Works',
    producers: ['Tenjin Publishing'],
    genres: ['Action', 'Martial Arts', 'School', 'Shounen', 'Drama'],
    episodeTitles: [
      'Best in Your Region',
      'The Second Years',
      'Ordinary Here',
      'Form and Function',
      'The Ranking Board',
      'Someone Has to Lose',
      'Off-Season',
      'The Instructor Who Never Placed',
      'Plateau',
      'Sparring Partner',
      'What Training Is For',
      'Thunderstep',
    ],
  },
  {
    titleEnglish: 'Paper Lanterns of Yomi',
    titleJapanese: '黄泉の紙灯篭',
    titleRomaji: 'Yomi no Kamidourou',
    synonyms: ['Yomi Lanterns'],
    tagline: 'One lantern per name. The list is long.',
    synopsis:
      'Once a year the river carries lanterns to the other side, one for each name a village is willing to release. Hanae has been the lantern-keeper for six years and has never once put her own family on the list. A supernatural drama, quiet and cold, about ritual as a way of postponing grief rather than processing it.',
    type: AnimeType.TV,
    status: AnimeStatus.COMPLETED,
    season: AnimeSeason.FALL,
    releaseYear: 2024,
    ageRating: AgeRating.R_17,
    source: AnimeSource.ORIGINAL,
    durationMinutes: 24,
    episodeCount: 10,
    hasDub: false,
    studio: 'Aoi Frame',
    producers: ['Lantern Partners'],
    genres: ['Supernatural', 'Drama', 'Horror', 'Historical', 'Mystery'],
    episodeTitles: [
      'One Lantern Per Name',
      'The Keeper',
      'Six Years',
      'Names Withheld',
      'Downstream',
      'What the River Returns',
      'The Other Side',
      'Hanae’s List',
      'Release',
      'Paper Lanterns',
    ],
  },
  {
    titleEnglish: 'Orbital Gardeners',
    titleJapanese: '軌道の庭師',
    titleRomaji: 'Kidou no Niwashi',
    synonyms: [],
    tagline: 'Somebody has to keep the trees alive.',
    synopsis:
      'The greenhouse ring of station Kasumi is maintained by three people, a maintenance drone with a personality fault, and an increasingly opinionated colony of bees. Nothing much goes wrong. That is largely the point. A gentle science fiction comedy about competent people doing unglamorous work extremely well.',
    type: AnimeType.ONA,
    status: AnimeStatus.ONGOING,
    season: AnimeSeason.SPRING,
    releaseYear: 2026,
    ageRating: AgeRating.G,
    source: AnimeSource.WEB_MANGA,
    durationMinutes: 15,
    episodeCount: 8,
    hasDub: false,
    studio: 'Aoi Frame',
    producers: ['Bluewave Records'],
    genres: ['Sci-Fi', 'Comedy', 'Slice of Life', 'Iyashikei'],
    episodeTitles: [
      'The Bees Have Opinions',
      'Personality Fault',
      'Humidity Control',
      'Three People and a Drone',
      'Pollination Week',
      'The Ring at Night',
      'Nothing Much Goes Wrong',
      'Harvest',
    ],
  },
  {
    titleEnglish: 'Fangs of the Silver Moon',
    titleJapanese: '銀月の牙',
    titleRomaji: 'Gingetsu no Kiba',
    synonyms: ['Silver Moon'],
    tagline: 'The treaty held for a century. It has nine days left.',
    synopsis:
      'The truce between the mountain clans and the lowland cities was signed by people who are all long dead, and renewed every hundred years by whoever happens to be holding the seal. This year the seal is held by a seventeen-year-old who was never meant to inherit it. A political fantasy about the machinery of peace, and how much of it runs on nothing but habit.',
    type: AnimeType.TV,
    status: AnimeStatus.UPCOMING,
    season: AnimeSeason.WINTER,
    releaseYear: 2027,
    ageRating: AgeRating.R_17,
    source: AnimeSource.LIGHT_NOVEL,
    durationMinutes: 24,
    episodeCount: 6,
    hasDub: false,
    studio: 'Hoshikawa Animation',
    producers: ['Hoshizora Media'],
    genres: ['Fantasy', 'Action', 'Drama', 'Historical', 'Supernatural'],
    episodeTitles: [
      'Nine Days',
      'Whoever Holds the Seal',
      'The Mountain Clans',
      'Signed by the Dead',
      'Renewal',
      'Silver Moon',
    ],
  },
  {
    titleEnglish: 'Echo Protocol Zero',
    titleJapanese: 'エコー・プロトコル・ゼロ',
    titleRomaji: 'Ekoo Purotokoru Zero',
    synonyms: ['EP0'],
    tagline: 'The machine remembers the pilot. That was not in the specification.',
    synopsis:
      'Frame units are supposed to reset between pilots. Unit 04 does not, and has been quietly accumulating eleven years of other people’s reflexes. When it is assigned to a rookie, the question stops being whether the machine is malfunctioning and becomes whether anyone is willing to say so out loud. A mecha drama concerned less with combat than with the chain of command that keeps signing off on it.',
    type: AnimeType.TV,
    status: AnimeStatus.COMPLETED,
    season: AnimeSeason.SUMMER,
    releaseYear: 2024,
    ageRating: AgeRating.R_17,
    source: AnimeSource.ORIGINAL,
    durationMinutes: 24,
    episodeCount: 12,
    hasDub: true,
    studio: 'Studio Karakuri',
    producers: ['Kagami Broadcasting', 'Tenjin Publishing'],
    genres: ['Mecha', 'Sci-Fi', 'Psychological', 'Drama', 'Action'],
    episodeTitles: [
      'Unit 04',
      'Reset Failure',
      'Eleven Years of Reflexes',
      'The Rookie',
      'Not in the Specification',
      'Chain of Command',
      'Someone Signed Off',
      'Muscle Memory',
      'The Pilots Before',
      'Say It Out Loud',
      'Decommission',
      'Echo Protocol Zero',
    ],
  },
  {
    titleEnglish: 'Summer of Falling Stars',
    titleJapanese: '流星の夏',
    titleRomaji: 'Ryuusei no Natsu',
    synonyms: [],
    tagline: 'Six weeks, one telescope, and a promise nobody intends to keep.',
    synopsis:
      'Four classmates agree to spend their last summer before graduation building a telescope good enough to photograph a meteor shower, mostly as an excuse to avoid talking about September. A romance and coming-of-age story about the things people build together specifically so they do not have to say anything.',
    type: AnimeType.MOVIE,
    status: AnimeStatus.COMPLETED,
    season: AnimeSeason.SUMMER,
    releaseYear: 2025,
    ageRating: AgeRating.PG,
    source: AnimeSource.ORIGINAL,
    durationMinutes: 108,
    episodeCount: 1,
    hasDub: true,
    studio: 'Studio Lumen',
    producers: ['Lantern Partners', 'Bluewave Records'],
    genres: ['Romance', 'Drama', 'Slice of Life', 'School', 'Shoujo'],
    episodeTitles: ['Summer of Falling Stars'],
  },
  {
    titleEnglish: 'Ironheart Meridian',
    titleJapanese: 'アイアンハート・メリディアン',
    titleRomaji: 'Aianhaato Meridian',
    synonyms: ['Ironheart'],
    tagline: 'A city that runs on debt, and the woman auditing it.',
    synopsis:
      'Meridian City runs on a ledger that predates its own founding charter, and forensic accountant Saya Kurogane has been hired to close a discrepancy of four hundred units. The discrepancy is the least interesting thing she finds. A dense, methodical thriller about financial machinery as an instrument of control, told without a single chase scene.',
    type: AnimeType.TV,
    status: AnimeStatus.ONGOING,
    season: AnimeSeason.FALL,
    releaseYear: 2026,
    ageRating: AgeRating.R_PLUS,
    source: AnimeSource.NOVEL,
    durationMinutes: 24,
    episodeCount: 10,
    hasDub: false,
    studio: 'Nova Sakura',
    producers: ['Hoshizora Media', 'Kagami Broadcasting'],
    genres: ['Thriller', 'Mystery', 'Psychological', 'Drama', 'Seinen'],
    episodeTitles: [
      'Four Hundred Units',
      'The Founding Charter',
      'Discrepancy',
      'Ledger Entries 1899–1904',
      'The Auditor',
      'Nothing Illegal Happened',
      'Compound Interest',
      'Who Holds the Note',
      'Settlement',
      'Ironheart Meridian',
    ],
  },
];

/** Invented, anime-community-flavoured progression. Fully admin-editable. */
export const RANKS: Array<{ name: string; requiredMana: number; icon: string; color: string; description: string }> = [
  { name: 'Drifter', requiredMana: 0, icon: '🌑', color: '#9ba0b5', description: 'Just arrived. Everyone starts here.' },
  { name: 'Initiate', requiredMana: 100, icon: '🌘', color: '#8ee3ef', description: 'Found your footing.' },
  { name: 'Seeker', requiredMana: 350, icon: '🌗', color: '#4dabf7', description: 'Actively exploring the catalogue.' },
  { name: 'Adept', requiredMana: 800, icon: '🌖', color: '#7c5cff', description: 'A recognised regular.' },
  { name: 'Vanguard', requiredMana: 1600, icon: '🌕', color: '#22e1c8', description: 'Shaping the conversation.' },
  { name: 'Sentinel', requiredMana: 3000, icon: '⭐', color: '#ffd93d', description: 'Trusted by the community.' },
  { name: 'Ascendant', requiredMana: 5500, icon: '✨', color: '#ff7eb3', description: 'Rarely matched.' },
  { name: 'Luminary', requiredMana: 9000, icon: '💫', color: '#ffa94d', description: 'A fixture of the board.' },
  { name: 'Eternal', requiredMana: 15000, icon: '🔥', color: '#ff4d5e', description: 'The highest standing there is.' },
];

export const MANA_RULES: Array<{ event: ManaEvent; amount: number; dailyLimit: number; description: string }> = [
  { event: ManaEvent.DAILY_LOGIN, amount: 5, dailyLimit: 5, description: 'Signing in each day.' },
  { event: ManaEvent.EPISODE_COMMENT, amount: 3, dailyLimit: 30, description: 'Commenting on an episode or a title.' },
  { event: ManaEvent.COMMUNITY_COMMENT, amount: 3, dailyLimit: 30, description: 'Commenting on a community post.' },
  { event: ManaEvent.COMMUNITY_POST, amount: 15, dailyLimit: 45, description: 'Publishing a community post.' },
  { event: ManaEvent.RECEIVED_UPVOTE, amount: 2, dailyLimit: 100, description: 'Someone upvoted your contribution.' },
  { event: ManaEvent.POLL_VOTE, amount: 1, dailyLimit: 10, description: 'Voting in a community poll.' },
  {
    event: ManaEvent.EPISODE_COMPLETED,
    amount: 4,
    dailyLimit: 60,
    // Only granted when playback is proxied through us and therefore verifiable.
    description: 'Finishing an episode (verified playback only).',
  },
  { event: ManaEvent.RATING_SUBMITTED, amount: 2, dailyLimit: 20, description: 'Rating a title.' },
  { event: ManaEvent.ANIME_REQUEST_APPROVED, amount: 25, dailyLimit: 0, description: 'A title you requested went live.' },
  { event: ManaEvent.ADMIN_ADJUSTMENT, amount: 0, dailyLimit: 0, description: 'Manual adjustment by staff.' },
];

export const COMMUNITY_CATEGORIES: Array<{
  name: string;
  description: string;
  color: string;
  icon: string;
  staffOnly?: boolean;
}> = [
  { name: 'Updates', description: 'Announcements from the team.', color: '#22e1c8', icon: '📣', staffOnly: true },
  { name: 'General', description: 'Anything that does not fit elsewhere.', color: '#7c5cff', icon: '💬' },
  { name: 'Suggestion', description: 'Ideas for improving the site.', color: '#51cf66', icon: '💡' },
  { name: 'Question', description: 'Ask the community.', color: '#4dabf7', icon: '❓' },
  { name: 'Discussion', description: 'Longer-form conversation about a series.', color: '#ff7eb3', icon: '🗯️' },
  { name: 'Feedback', description: 'Tell us what is not working.', color: '#ffa94d', icon: '📝' },
  { name: 'Tier List', description: 'Rank things. Defend your choices.', color: '#ffd93d', icon: '🏆' },
  { name: 'Poll', description: 'Put it to a vote.', color: '#9775fa', icon: '📊' },
  { name: 'Matchup', description: 'Head-to-head. Pick a side.', color: '#ff4d5e', icon: '⚔️' },
  { name: 'Seasonal', description: 'What is airing right now.', color: '#a9e34b', icon: '🍃' },
  { name: 'Recommend', description: 'Suggest something worth watching.', color: '#8ee3ef', icon: '✅' },
];

/**
 * Every display slot the frontend knows how to render. All start disabled with
 * empty identifiers, so nothing renders until the operator supplies their own
 * AdSense details in the admin panel.
 */
export const AD_PLACEMENTS: Array<{ key: string; name: string; description: string; order: number }> = [
  { key: 'home_below_hero', name: 'Home — below hero', description: 'Directly under the homepage slider.', order: 10 },
  { key: 'home_in_feed', name: 'Home — between episode rails', description: 'Between Latest Episodes and the next rail.', order: 20 },
  { key: 'home_between_grids', name: 'Home — between anime grids', description: 'Between two catalogue grids.', order: 30 },
  { key: 'home_footer', name: 'Home — above footer', description: 'Last slot on the homepage.', order: 40 },
  { key: 'browse_top', name: 'Browse — above results', description: 'Above the results grid on list pages.', order: 50 },
  { key: 'browse_in_grid', name: 'Browse — inside results grid', description: 'Injected into the results grid.', order: 60 },
  { key: 'anime_detail_top', name: 'Anime — below synopsis', description: 'On the anime details page.', order: 70 },
  { key: 'anime_detail_episodes', name: 'Anime — between episode sections', description: 'Between episode list blocks.', order: 80 },
  { key: 'watch_above_player', name: 'Watch — above player', description: 'Directly above the video player.', order: 90 },
  { key: 'watch_below_player', name: 'Watch — below player', description: 'Directly below the video player.', order: 100 },
  { key: 'watch_sidebar', name: 'Watch — sidebar', description: 'Large screens only.', order: 110 },
  { key: 'watch_below_comments', name: 'Watch — below comments', description: 'Under the comment thread.', order: 120 },
  { key: 'community_list', name: 'Community — post list', description: 'Inside the community board list.', order: 130 },
  { key: 'search_results', name: 'Search — results', description: 'On the search results page.', order: 140 },
];

export const SITE_SETTINGS: Array<{
  key: string;
  value: unknown;
  group: string;
  label: string;
  isPublic: boolean;
}> = [
  { key: 'site.name', value: 'AniZora', group: 'general', label: 'Site name', isPublic: true },
  { key: 'site.tagline', value: 'Stream anime in stunning quality', group: 'general', label: 'Tagline', isPublic: true },
  {
    key: 'site.description',
    value: 'Watch anime online in high quality with multiple audio options, subtitles and a community that actually talks about it.',
    group: 'general',
    label: 'Meta description',
    isPublic: true,
  },
  { key: 'site.defaultTitleLanguage', value: 'ENGLISH', group: 'general', label: 'Default title language', isPublic: true },
  { key: 'player.autoplayNext', value: true, group: 'player', label: 'Autoplay next episode by default', isPublic: true },
  { key: 'player.autoSkipIntro', value: false, group: 'player', label: 'Auto-skip intro by default', isPublic: true },
  { key: 'player.defaultQuality', value: 'auto', group: 'player', label: 'Preferred starting quality', isPublic: true },
  { key: 'player.rememberVolume', value: true, group: 'player', label: 'Remember volume between sessions', isPublic: true },
  { key: 'community.enabled', value: true, group: 'community', label: 'Community board enabled', isPublic: true },
  { key: 'community.requireVerifiedEmail', value: false, group: 'community', label: 'Require a verified email to post', isPublic: true },
  { key: 'comments.enabled', value: true, group: 'community', label: 'Comments enabled', isPublic: true },
  { key: 'requests.enabled', value: true, group: 'community', label: 'Anime requests enabled', isPublic: true },
  { key: 'downloads.enabled', value: true, group: 'media', label: 'Show download links when configured', isPublic: true },
  { key: 'seo.robots', value: 'index,follow', group: 'seo', label: 'Default robots directive', isPublic: true },
  { key: 'contact.replyWindowDays', value: 3, group: 'support', label: 'Stated reply window (days)', isPublic: true },
];

export const CONTACT_CATEGORIES = Object.values(ContactCategory);
